### ISSUE TITLE
App crashes on dev start: Cannot find module '../credentials'

### ISSUE THREAD

**Issue by ghost** [gitmatch/gitmatch#14]
when launching the application with `nam run dev` you get following message:

```
Error: Cannot find module '../credentials'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Moritz/gitmatch/lib/development.js:1:81)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by ghost** [comment]
Sorry, should have read the readme more closely
